# Generated by Django 2.0.4 on 2018-07-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_substitute_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ImageLink',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2017/02/14/07/44/cake-2065046_1280.jpg', max_length=150),
        ),
    ]
