# Generated by Django 2.0.4 on 2018-04-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=40, unique=True)),
                ('CatNum', models.PositiveSmallIntegerField()),
                ('Places', models.CharField(max_length=40, null=True)),
                ('Stores', models.CharField(max_length=40, null=True)),
                ('Grade', models.CharField(max_length=1, null=True)),
                ('Link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdNum', models.PositiveSmallIntegerField()),
                ('SubNum', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
