# Generated by Django 2.0.4 on 2018-07-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='UserId',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
