# Generated by Django 2.0.4 on 2018-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
